### ISSUE TITLE
Sample code update - include appears to be incorrect

### ISSUE THREAD

**Issue by openclipboard** [quentinsf/pygarmin#12]
The sample code has: from:

`garmin import garmin, link, logger`

It appears this will work:

`from pygarmin import garmin, link, logger`

instead.

A slightly more expanded example might be helpful, for example.   

```
# Print the tracks
print("Tracks:")
for track in tracks:
    print(track)
    if(type(track)==type(garmin.mod_datatype.D304())):
        print(".....lat/lon degrees: ",end='')
        print(track.get_posn().as_degrees())
        print(".....heartrate: ",end='')
        print(track.heart_rate)
        print(".....datetime: ",end='')
        print(track.get_datetime())
```

**Comment by fvdbeek** [comment]
The module name is fixed in commit 161a11c. And regarding  your proposal for a more elaborate example, please feel free to open a PR. 

However I'm afraid your example isn't generic enough, because a specific datatype and the support of heart rate is assumed. Moreover, I doubt an expanded example should be included in the README. I only touched the surface on purpose, because developers can find more in depth information in the API documentation and examples in the included Pygarmin command line application. And end users that only want to print tracks don't have to program, but can use the command line program.
