### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by R1BGW** [quentinsf/pygarmin#8]
Hello.I have a Garmin strike plus 4 echo sounder. I know that it connects via a serial port at 115200 baud. At the moment, there is only one utility that can work with it 50/50% (GARMIN DNR). I periodically pop up errors and saving the GPX format is crooked. The question itself is: what protocols does your programme  support?
![Скриншот 14-01-2024 182114](https://github.com/quentinsf/pygarmin/assets/114905528/f2b244d3-d99c-4005-9376-b909a471d335)
Screenshot of the info of the GARMIN DNR program
When typing a command pygarmin --version , writes pygarmin version 0.3 although it has been updated to version 1.1.2 ,what's wrong?
Thanks . 
With respect . Vadim.

**Comment by quentinsf** [comment]
Hi Vadim - 
Folkert's the knowledgeable guy, since he's done all the recent work on this.  But the file [src/garmin/garmin.py](https://github.com/quentinsf/pygarmin/blob/master/src/garmin/garmin.py) has a class for each supported protocol, so you could try searching that.
On the version front, yes, that is a bit confusing!  the pygarmin script now uses the 'garmin' module, and they have different versions: it's the garmin module that's now at 1.1.2.

Folkert - I suggest we might make the versions match, but for now I've pushed a small fix to list both of them:
```
$ pygarmin --version
pygarmin version 0.3 using garmin module version 1.1.2
```
but feel free to replace it with something else if preferred!

Quentin

**Comment by R1BGW** [comment]
Hello. I can't connect via the COM port.
![Скриншот 15-01-2024 084024](https://github.com/quentinsf/pygarmin/assets/114905528/38b82ac6-fdc2-4e7d-8f09-5892d1d1d8fe)

**Comment by fvdbeek** [comment]
I only now see this issue by accident, because I  didn't receive a notification. From the screenshot, it appears that the following protocols and datatypes are supported:

- Link protocol: L001
- Waypoint transfer protocol: A100, D110
- Route transfer protocol: A201, D202, D110
- Track log transfer protocol: A301, D312, D302
- Proximity: A400, D110
- Date and time initialization protocol: A600, D600
- Position initialization protocol: A700, D700
- PVT protocol: A800, D800

Pygarmin supports all of these, and more. The usage of the command-line application is documented [here](https://pygarmin.readthedocs.io/en/latest/index.html). For example, to check the protocol capabilities use:

`pygarmin protocols`

The application uses the Garmin USB protocol by default. If your device doesn't support this, you can use the serial port with:

`pygarmin -p COM1 protocols` (COM1 for the MS Windows serial port)

Please let me know if this works, because the only devices I have tested the code with is an Etrex Legend C and a Forerunner 305 with a computer running GNU/Linux.

The default baudrate is 9600. Pygarmin is able to operate with other baudrates, but this isn't supported in the command line application.

By the way, the application supports exporting to GPX, including the Garmin extensions. Currently I am writing support for importing from GPX, as well as exporting to FIT.

In the future I will use the same version numbers for the pygarmin library and the command-line application.

**Comment by R1BGW** [comment]
Здравствуйте. Я изначально пошел не тем путем . Я не программист , но меня что то толкнуло на изучение Python . Приобрел несколько "руководств по выращиванию рептилии (пресмыкающего) " (книги и уроки из сети). 
Изначально необходимо загрузить модули для pygarmin  и  garmin . У меня все в итоге получилось подключить эхолот и туристический навигатор . Следующий шаг написать скрипт с модулем Tkinter или PyQt5 или 6. Спасибо за поддержку и помощь.
Эхолот :Garmin Striker 4 plus  Навигатор : Garmin GPS MAP60 CSx .
![Скриншот 05-03-2024 114632](https://github.com/quentinsf/pygarmin/assets/114905528/47c649b8-e254-4e0a-9cde-2575250299f9)
![Скриншот 05-03-2024 120144](https://github.com/quentinsf/pygarmin/assets/114905528/d1a53e2f-6d3e-40db-a930-e30cbc7f937f)

**Comment by R1BGW** [comment]
![Скриншот 05-03-2024 114632](https://github.com/quentinsf/pygarmin/assets/114905528/4f32fdde-d10f-4f46-85ce-c616fb350cde)
![Скриншот 05-03-2024 120144](https://github.com/quentinsf/pygarmin/assets/114905528/81c1bbd0-5761-4c3b-88aa-1ce9cd75ee0e)
I managed to connect and download information from the Garmin striker 4 plus and the garmin map 60csx travel navigator. I had to study the library code and download the necessary modules.

**Comment by fvdbeek** [comment]
I don't understand Russian, but from an online translation I understand that you managed to get both your devices recognized by pygarmin and now you plan to write a graphical user interface with PyQt. Good luck!
